-- ialert revise data on ialert_audit query

UPDATE ialert_audit SET process='Silicon Injection Process', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='57';
UPDATE ialert_audit SET process='Cutting and crimping ', section='fpsection2', falp_group='First Process' WHERE id='92';
UPDATE ialert_audit SET process='Cutting and crimping ', section='fpsection2', falp_group='First Process' WHERE id='310';
UPDATE ialert_audit SET process='Loopings', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='369';
UPDATE ialert_audit SET process='Auto SAM', section='fpsection1', falp_group='First Process' WHERE id='396';
UPDATE ialert_audit SET process='Point Marking ', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='401';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp2section7', falp_group='Secondary 2 Process' WHERE id='463';
UPDATE ialert_audit SET process='Assurance', section='section7', falp_group='QA' WHERE id='508';
UPDATE ialert_audit SET process='Manual crimping ', section='fpsection8', falp_group='First Process' WHERE id='583';
UPDATE ialert_audit SET process='Wire setting ', section='section1', falp_group='FAP1' WHERE id='709';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp1section3', falp_group='Secondary 1 Process' WHERE id='738';
UPDATE ialert_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='908';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp2section6', falp_group='Secondary 2 Process' WHERE id='910';
UPDATE ialert_audit SET process='Gomusen Insertion', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='950';
UPDATE ialert_audit SET process='NS-C', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='1252';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='1742';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='1759';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='1933';
UPDATE ialert_audit SET process='Cutting and crimping ', section='fpsection5', falp_group='First Process' WHERE id='2474';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp1section3', falp_group='Secondary 1 Process' WHERE id='2553';
UPDATE ialert_audit SET process='Auto SAM', section='fpsection6', falp_group='First Process' WHERE id='2561';
UPDATE ialert_audit SET process='Point Marking ', section='sp2section7', falp_group='Secondary 2 Process' WHERE id='2562';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='2643';
UPDATE ialert_audit SET process='Sub-Assembly ', section='section5', falp_group='FAP2' WHERE id='2686';
UPDATE ialert_audit SET process='Cutting and crimping ', section='fpsection5', falp_group='First Process' WHERE id='2687';
UPDATE ialert_audit SET process='Gomusen Insertion', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='2745';
UPDATE ialert_audit SET process='Waterproof pad fitting', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='3018';
UPDATE ialert_audit SET process='Waterproof pad fitting', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='3046';
UPDATE ialert_audit SET process='Sub-Assembly ', section='section1', falp_group='FAP1' WHERE id='3170';
UPDATE ialert_audit SET process='Auto SAM ', section='fpsection2', falp_group='First Process' WHERE id='3269';
UPDATE ialert_audit SET process='Point Marking ', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='3426';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='3933';
UPDATE ialert_audit SET process='QC Verification', section='qa-initial', falp_group='QA' WHERE id='4010';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='4047';
UPDATE ialert_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='4057';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp2section3', falp_group='Secondary 2 Process' WHERE id='4367';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='4434';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='4622';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='4726';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='4727';
UPDATE ialert_audit SET process='Cutting and crimping ', section='fpsection3', falp_group='First Process' WHERE id='5358';
UPDATE ialert_audit SET process='Auto Sam', section='fpsection2', falp_group='First Process' WHERE id='5526';
UPDATE ialert_audit SET process='Manual Insertion Gomusen', section='sp2section2', falp_group='Secondary 2 Process' WHERE id='5576';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp1section3', falp_group='Secondary 1 Process' WHERE id='5669';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp1section2', falp_group='Secondary 1 Process' WHERE id='5723';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='5872';
UPDATE ialert_audit SET process='Gomusen Insertion', section='sp2section8', falp_group='Secondary 2 Process' WHERE id='6219';
UPDATE ialert_audit SET process='Loopings', section='sp1section8', falp_group='Secondary 1 Process' WHERE id='6338';
UPDATE ialert_audit SET process='Loopings', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='6339';
UPDATE ialert_audit SET process='Shieldwire Taping', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='6451';
UPDATE ialert_audit SET process='Point Marking ', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='6665';
UPDATE ialert_audit SET process='Sub-Assembly ', section='section5', falp_group='FAP4' WHERE id='6818';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='7213';
UPDATE ialert_audit SET process='Bukumi ', section='fpsection6', falp_group='First Process' WHERE id='7312';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp1section9', falp_group='Secondary 1 Process' WHERE id='7465';
UPDATE ialert_audit SET process='Point Marking ', section='sp2section6', falp_group='Secondary 2 Process' WHERE id='7602';
UPDATE ialert_audit SET process='Loopings', section='sp1section9', falp_group='Secondary 1 Process' WHERE id='7677';
UPDATE ialert_audit SET process='Loopings', section='sp1section9', falp_group='Secondary 1 Process' WHERE id='7678';
UPDATE ialert_audit SET process='Auto Sam', section='fpsection9', falp_group='First Process' WHERE id='7910';
UPDATE ialert_audit SET process='Point Marking ', section='sp2section7', falp_group='Secondary 2 Process' WHERE id='7936';
UPDATE ialert_audit SET process='Joint Taping ', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='7937';
UPDATE ialert_audit SET process='Point Marking ', section='sp2section7', falp_group='Secondary 2 Process' WHERE id='7960';
UPDATE ialert_audit SET process='Manual Crimping', section='sp1section2', falp_group='Secondary 1 Process' WHERE id='8122';
UPDATE ialert_audit SET process='Bukumi ', section='fpsection4', falp_group='First Process' WHERE id='8352';
UPDATE ialert_audit SET process='Silicon Injection Process', section='sp2section7', falp_group='Secondary 2 Process' WHERE id='8552';

-- ialert revise data on ialert_line_audit query

UPDATE ialert_line_audit SET process='Loopings', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='9';
UPDATE ialert_line_audit SET process='Loopings', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='174';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection6', falp_group='First Process' WHERE id='263';
UPDATE ialert_line_audit SET process='Casting', section='sp2section8', falp_group='Secondary 2 Process' WHERE id='274';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='428';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='429';
UPDATE ialert_line_audit SET process='Silicon Injection', section='sp1section4', falp_group='Secondary 1 Process' WHERE id='556';
UPDATE ialert_line_audit SET process='Silicon Injection', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='625';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='1540';
UPDATE ialert_line_audit SET process='Hirose', section='sp1section4', falp_group='Secondary 1 Process' WHERE id='1621';
UPDATE ialert_line_audit SET process='Parts ', section='fpsection8', falp_group='First Process' WHERE id='1641';
UPDATE ialert_line_audit SET process='Loopings ', section='sp2section5', falp_group='Secondary 2 Process' WHERE id='2853';
UPDATE ialert_line_audit SET process='Wire setting ', section='section5', falp_group='FAP4' WHERE id='2910';
UPDATE ialert_line_audit SET process='initial/Bukumi ', section='section5', falp_group='FAP2' WHERE id='3919';
UPDATE ialert_line_audit SET process='N/A', section='fpsection1', falp_group='First Process' WHERE id='4019';
UPDATE ialert_line_audit SET process='Completion ', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='4440';
UPDATE ialert_line_audit SET process='Completion ', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='4441';
UPDATE ialert_line_audit SET process='Dip Soldering ', section='sp2section8', falp_group='Secondary 2 Process' WHERE id='5429';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section4', falp_group='FAP3' WHERE id='5677';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section1', falp_group='FAP1' WHERE id='6139';
UPDATE ialert_line_audit SET process='Silicon', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='6217';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='6566';
UPDATE ialert_line_audit SET process='Silicon', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='6953';
UPDATE ialert_line_audit SET process='Shieldwire ', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='6984';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section4', falp_group='FAP3' WHERE id='7100';
UPDATE ialert_line_audit SET process='Wire setting/Sub-assy ', section='section1', falp_group='FAP2' WHERE id='7210';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section4', falp_group='FAP3' WHERE id='7494';
UPDATE ialert_line_audit SET process='Shieldwire ', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='7975';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section5', falp_group='FAP4' WHERE id='8239';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section9', falp_group='FAP4' WHERE id='8370';
UPDATE ialert_line_audit SET process='Auto SAM ', section='fpsection5', falp_group='First Process' WHERE id='8819';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='8820';
UPDATE ialert_line_audit SET process='Mid-Stripping ', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='8828';
UPDATE ialert_line_audit SET process='Mid-Stripping ', section='sp1section3', falp_group='Secondary 1 Process' WHERE id='8910';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection2', falp_group='First Process' WHERE id='8974';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section1', falp_group='FAP1' WHERE id='9494';
UPDATE ialert_line_audit SET process='Shieldwire taping. ', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='9688';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='10017';
UPDATE ialert_line_audit SET process='Completion', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='10040';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='10099';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='10100';
UPDATE ialert_line_audit SET process='Water proof pad press', section='sp2section4', falp_group='Secondary 2 Process' WHERE id='10425';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='10515';
UPDATE ialert_line_audit SET process='initial/Bukumi ', section='section8', falp_group='Factory 2' WHERE id='10685';
UPDATE ialert_line_audit SET process='Bolt fitting ', section='fpsection8', falp_group='First Process' WHERE id='10687';
UPDATE ialert_line_audit SET process='Shikakari Handler', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='10874';
UPDATE ialert_line_audit SET process='N/A', section='fpsection5', falp_group='First Process' WHERE id='11985';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection5', falp_group='First Process' WHERE id='12299';
UPDATE ialert_line_audit SET process='Picking', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='13078';
UPDATE ialert_line_audit SET process='initial/Bukumi ', section='section6', falp_group='FAP3' WHERE id='13102';
UPDATE ialert_line_audit SET process='Bending Machine', section='fpsection6', falp_group='First Process' WHERE id='13305';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section9', falp_group='FAP2' WHERE id='13528';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection6', falp_group='First Process' WHERE id='13536';
UPDATE ialert_line_audit SET process='Shieldwire', section='sp1section3', falp_group='Secondary 1 Process' WHERE id='14198';
UPDATE ialert_line_audit SET process='Gomusen Insertion ', section='sp1section5', falp_group='Secondary 1 Process' WHERE id='14201';
UPDATE ialert_line_audit SET process='Shieldwire', section='sp2section6', falp_group='Secondary 2 Process' WHERE id='14315';
UPDATE ialert_line_audit SET process='Loopings', section='sp1section9', falp_group='Secondary 1 Process' WHERE id='14669';
UPDATE ialert_line_audit SET process='Pulling Strength', section='fpsection6', falp_group='First Process' WHERE id='14925';
UPDATE ialert_line_audit SET process='QA', section='qa-initial', falp_group='QA' WHERE id='14963';
UPDATE ialert_line_audit SET process='Auto SAM', section='fpsection6', falp_group='First Process' WHERE id='15379';
UPDATE ialert_line_audit SET process='Twisting', section='sp1section2', falp_group='Secondary 1 Process' WHERE id='15461';
UPDATE ialert_line_audit SET process='Sub-Assembly ', section='section1', falp_group='FAP1' WHERE id='15561';
UPDATE ialert_line_audit SET process='Manual Crimping', section='sp1section2', falp_group='Secondary 1 Process' WHERE id='15802';
UPDATE ialert_line_audit SET process='Joint Crimping ', section='sp1section1', falp_group='Secondary 1 Process' WHERE id='16047';
UPDATE ialert_line_audit SET process='N/A', section='fpsection5', falp_group='First Process' WHERE id='16376';
UPDATE ialert_line_audit SET process='Weld Taping', section='sp1section2', falp_group='Secondary 1 Process' WHERE id='17479';

DELETE FROM ialert_line_audit WHERE id='5604' and section='';
DELETE FROM ialert_line_audit WHERE id='5632' and section='';
DELETE FROM ialert_line_audit WHERE id='5633' and section='';
